# Generated by Django 4.0 on 2021-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertreviewmodel',
            name='review',
            field=models.TextField(max_length=256),
        ),
    ]
